---
title: APPX
description: Removal of APPX packages
privilege: TrustedInstaller
actions:
  
  - !writeStatus: {status: "Removing Appx Packages"}
  - !powerShell:
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 48
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.Windows.SecureAssessmentBrowser',
        'Microsoft.Windows.PeopleExperienceHost',
        'Microsoft.WindowsCamera',
        'MicrosoftWindows.Client.WebExperience',
        'Microsoft.WidgetsPlatformRuntime',
        'Microsoft.WindowsAlarms',
        'Microsoft.WindowsMaps',
        'Microsoft.MicrosoftStickyNotes',
        'microsoft.windowscommunicationsapps',
        'Microsoft.People',
        'Microsoft.BingNews',
        'Microsoft.BingSearch',
        'Microsoft.BingWeather',
        'Microsoft.MicrosoftSolitaireCollection',
        'Microsoft.WindowsFeedbackHub',
        'Microsoft.GetHelp',
        'Microsoft.Getstarted',
        'Microsoft.Todos',
        'Microsoft.PowerAutomateDesktop',
        'Microsoft.549981C3F5F10', # Cortana
        'MicrosoftCorporationII.QuickAssist',
        'MicrosoftCorporationII.MicrosoftFamily',
        'Microsoft.ZuneMusic',
        'Microsoft.ZuneVideo',
        'Microsoft.WindowsSoundRecorder',
        'Clipchamp.Clipchamp',
        'Microsoft.Whiteboard',
        'Microsoft.MicrosoftTeamsforSurfaceHub',
        'MicrosoftCorporationII.MailforSurfaceHub',
        'Microsoft.MicrosoftPowerBIForWindows',
        'Microsoft.SkypeApp',
        'Microsoft.MicrosoftOfficeHub',
        'Microsoft.Office.Excel',
        'Microsoft.Office.PowerPoint',
        'Microsoft.Office.Word',
        'Microsoft.Office.OneNote',
        'Microsoft.OutlookForWindows',
        'SpotifyAB.SpotifyMusic',
        'OutlookPWA',
        'Flipgrid',
        'Microsoft.Microsoft3DViewer',
        'Microsoft.Advertising',
        'MixedReality.Portal',
        'Microsoft.MSPaint', # Paint 3D
        'MicrosoftTeams',
        'MSTeams', # New Teams
        'Microsoft.StartExperiencesApp'
      )

  - !writeStatus: {status: "Removing Photos"}
  - !powerShell:
    option: "remove-appx-photos"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'Microsoft.Windows.Photos'

  - !writeStatus: {status: "Removing Dev Home", option: "remove-appx-devhome"}
  - !powerShell:
    option: "remove-appx-devhome"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'Microsoft.Windows.DevHome'
    
  - !writeStatus: {status: "Removing Xbox Apps", option: "remove-appx-xbox"}
  - !powerShell:
    option: "remove-appx-xbox"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.Xbox',
        'Microsoft.XboxApp', # Xbox Console Companion is deprecated
        'Microsoft.GamingApp',
        'Microsoft.XboxGameCallableUI'
      )
  - !appx: {name: 'Microsoft.XboxGameCallableUI*', type: family, weight: 10, option: "remove-appx-xbox"}

    #139
  - !registryValue: {path: 'HKCR\ms-gamebar', value: '', type: REG_SZ, data: 'URL:ms-gamebar', option: "remove-appx-xbox"}
  - !registryValue: {path: 'HKCR\ms-gamebar', value: 'URL Protocol', type: REG_SZ, data: '', option: "remove-appx-xbox"}
  - !registryKey: {path: 'HKCR\ms-gamebar\shell\open\command', operation: add, option: "remove-appx-xbox"}
  - !registryValue: {path: 'HKCR\ms-gamebar', value: '', type: REG_SZ, data: '%SystemRoot%\System32\systray.exe', option: "remove-appx-xbox"}
  - !registryValue: {path: 'HKCU\Software\Microsoft\GameBar', value: 'ShowStartupPanel', type: REG_DWORD, data: '0', option: "remove-appx-xbox"}

  - !writeStatus: {status: "Removing Your Phone", option: "remove-appx-yourphone"}
  - !powerShell:
    option: "remove-appx-yourphone"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 20
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.YourPhone',
        'MicrosoftWindows.CrossDevice'
      )

  - !writeStatus: {status: "Removing Recall", option: "remove-appx-recall"}
  - !powerShell:
    option: "remove-appx-recall"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'MicrosoftWindows.Client.AIX'